<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }
</style>
<?php
// Создаём заголовок страницы, который загрузится в layout
$this->title = "Мои любимые фильмы";
$this->headTitle($this->title);
?>
<p><a href="<?php echo $this->url(array('controller'=>'index','action'=>'add'));?>">Добавить новый фильм</a></p>

<table>
    <tr>
        <th>Название</th>
        <th>Режиссёр</th>
        <th>&nbsp;</th>
    </tr>
    <?php
        // Создаём patrialLoop, передав массив фильмов, полученных от контроллера
        echo $this->partialLoop('partials/movie.phtml', $this->movies);
        echo $this->form;
    ?>
    
</table>