<?php
    // Создаём meta тег Content-Type
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
    // Указываем символ разделитель в теге title
    $this->headTitle()->setSeparator(' - ');
    // Определяем содержимое тега title
    $this->headTitle('Уроки по Zend Frameworkу');
    
    // Выводим doctype, который считывается из application.ini
    echo $this->doctype();
?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <?php
        // Выводим meta теги
        echo $this->headMeta();
    ?>
    <?php
        // Выводим заголовок сайта
        echo $this->headTitle();
    ?>
    <?php
        // Прикрепляем таблицу стилей
        echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css');
    ?>
</head>
<body>
    <?php
    // Применяем уже знакомый метод для проверки авторизации пользователя
    if (Zend_Auth::getInstance()->hasIdentity()) {
        $url = $this->url(array('controller'=>'auth', 'action'=>'logout'));
        // если пользователь авторизирован, показываем ему кнопку "Выход"
        echo "<a href=\"{$url}\">Выход</a>";
    }  
    ?>
    <div id="content">
        <h1>
        <?php
            // Выводим заголовок странице, который будем формировать в каждом view
            echo $this->escape($this->title);
        ?>
        </h1>
        <?php
            // Данная запись выводит содержимое view
            echo $this->layout()->content;
        ?>
    </div>
</body>
</html>
